server:
  port: ${PORT:8083}
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/json,text/html,text/plain

spring:
  application:
    name: user-service
  data:
    mongodb:
      # Sharing the users database with auth-service
      uri: ${MONGODB_URI:mongodb://localhost:27017/campus_notes_hub_users}

notes-service:
  url: ${NOTES_SERVICE_URL:http://localhost:8082}

logging:
  level:
    org.springframework.web: INFO
